//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevencWpf.ServicioWcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa", Namespace="http://schemas.datacontract.org/2004/07/SEVENC.Dominio.Entidades", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Empresa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ConcurrenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstaActivaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstaEliminadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte IdEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdRepresentanteLegalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreRepresentanteLegalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SevencWpf.ServicioWcf.Sucursal> SucursalesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SevencWpf.ServicioWcf.Usuario> UsuariosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Concurrencia {
            get {
                return this.ConcurrenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ConcurrenciaField, value) != true)) {
                    this.ConcurrenciaField = value;
                    this.RaisePropertyChanged("Concurrencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstaActiva {
            get {
                return this.EstaActivaField;
            }
            set {
                if ((this.EstaActivaField.Equals(value) != true)) {
                    this.EstaActivaField = value;
                    this.RaisePropertyChanged("EstaActiva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstaEliminada {
            get {
                return this.EstaEliminadaField;
            }
            set {
                if ((this.EstaEliminadaField.Equals(value) != true)) {
                    this.EstaEliminadaField = value;
                    this.RaisePropertyChanged("EstaEliminada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte IdEmpresa {
            get {
                return this.IdEmpresaField;
            }
            set {
                if ((this.IdEmpresaField.Equals(value) != true)) {
                    this.IdEmpresaField = value;
                    this.RaisePropertyChanged("IdEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdRepresentanteLegal {
            get {
                return this.IdRepresentanteLegalField;
            }
            set {
                if ((object.ReferenceEquals(this.IdRepresentanteLegalField, value) != true)) {
                    this.IdRepresentanteLegalField = value;
                    this.RaisePropertyChanged("IdRepresentanteLegal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreComercial {
            get {
                return this.NombreComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreComercialField, value) != true)) {
                    this.NombreComercialField = value;
                    this.RaisePropertyChanged("NombreComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreRepresentanteLegal {
            get {
                return this.NombreRepresentanteLegalField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreRepresentanteLegalField, value) != true)) {
                    this.NombreRepresentanteLegalField = value;
                    this.RaisePropertyChanged("NombreRepresentanteLegal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUC {
            get {
                return this.RUCField;
            }
            set {
                if ((object.ReferenceEquals(this.RUCField, value) != true)) {
                    this.RUCField = value;
                    this.RaisePropertyChanged("RUC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SevencWpf.ServicioWcf.Sucursal> Sucursales {
            get {
                return this.SucursalesField;
            }
            set {
                if ((object.ReferenceEquals(this.SucursalesField, value) != true)) {
                    this.SucursalesField = value;
                    this.RaisePropertyChanged("Sucursales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SevencWpf.ServicioWcf.Usuario> Usuarios {
            get {
                return this.UsuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuariosField, value) != true)) {
                    this.UsuariosField = value;
                    this.RaisePropertyChanged("Usuarios");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sucursal", Namespace="http://schemas.datacontract.org/2004/07/SEVENC.Dominio.Entidades", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Sucursal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ConcurrenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SevencWpf.ServicioWcf.Empresa> EmpresasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsMatrizField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstaActivaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstaEliminadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdSucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Concurrencia {
            get {
                return this.ConcurrenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ConcurrenciaField, value) != true)) {
                    this.ConcurrenciaField = value;
                    this.RaisePropertyChanged("Concurrencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SevencWpf.ServicioWcf.Empresa> Empresas {
            get {
                return this.EmpresasField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresasField, value) != true)) {
                    this.EmpresasField = value;
                    this.RaisePropertyChanged("Empresas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsMatriz {
            get {
                return this.EsMatrizField;
            }
            set {
                if ((this.EsMatrizField.Equals(value) != true)) {
                    this.EsMatrizField = value;
                    this.RaisePropertyChanged("EsMatriz");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstaActiva {
            get {
                return this.EstaActivaField;
            }
            set {
                if ((this.EstaActivaField.Equals(value) != true)) {
                    this.EstaActivaField = value;
                    this.RaisePropertyChanged("EstaActiva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstaEliminada {
            get {
                return this.EstaEliminadaField;
            }
            set {
                if ((this.EstaEliminadaField.Equals(value) != true)) {
                    this.EstaEliminadaField = value;
                    this.RaisePropertyChanged("EstaEliminada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdSucursal {
            get {
                return this.IdSucursalField;
            }
            set {
                if ((this.IdSucursalField.Equals(value) != true)) {
                    this.IdSucursalField = value;
                    this.RaisePropertyChanged("IdSucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/SEVENC.Dominio.Entidades", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SevencWpf.ServicioWcf.Auditoria> AuditoriasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ConcurrenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SevencWpf.ServicioWcf.Empresa> EmpresasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstaActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstaBloqueadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstaEliminadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SevencWpf.ServicioWcf.Rol> RolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SevencWpf.ServicioWcf.SesionUsuario> SesionesUsuariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SevencWpf.ServicioWcf.Auditoria> Auditorias {
            get {
                return this.AuditoriasField;
            }
            set {
                if ((object.ReferenceEquals(this.AuditoriasField, value) != true)) {
                    this.AuditoriasField = value;
                    this.RaisePropertyChanged("Auditorias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Concurrencia {
            get {
                return this.ConcurrenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ConcurrenciaField, value) != true)) {
                    this.ConcurrenciaField = value;
                    this.RaisePropertyChanged("Concurrencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SevencWpf.ServicioWcf.Empresa> Empresas {
            get {
                return this.EmpresasField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresasField, value) != true)) {
                    this.EmpresasField = value;
                    this.RaisePropertyChanged("Empresas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsSistema {
            get {
                return this.EsSistemaField;
            }
            set {
                if ((this.EsSistemaField.Equals(value) != true)) {
                    this.EsSistemaField = value;
                    this.RaisePropertyChanged("EsSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstaActivo {
            get {
                return this.EstaActivoField;
            }
            set {
                if ((this.EstaActivoField.Equals(value) != true)) {
                    this.EstaActivoField = value;
                    this.RaisePropertyChanged("EstaActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstaBloqueado {
            get {
                return this.EstaBloqueadoField;
            }
            set {
                if ((this.EstaBloqueadoField.Equals(value) != true)) {
                    this.EstaBloqueadoField = value;
                    this.RaisePropertyChanged("EstaBloqueado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstaEliminado {
            get {
                return this.EstaEliminadoField;
            }
            set {
                if ((this.EstaEliminadoField.Equals(value) != true)) {
                    this.EstaEliminadoField = value;
                    this.RaisePropertyChanged("EstaEliminado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SevencWpf.ServicioWcf.Rol> Roles {
            get {
                return this.RolesField;
            }
            set {
                if ((object.ReferenceEquals(this.RolesField, value) != true)) {
                    this.RolesField = value;
                    this.RaisePropertyChanged("Roles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SevencWpf.ServicioWcf.SesionUsuario> SesionesUsuarios {
            get {
                return this.SesionesUsuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.SesionesUsuariosField, value) != true)) {
                    this.SesionesUsuariosField = value;
                    this.RaisePropertyChanged("SesionesUsuarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Auditoria", Namespace="http://schemas.datacontract.org/2004/07/SEVENC.Dominio.Entidades", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Auditoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SevencWpf.ServicioWcf.DetalleAuditoria> DetallesAuditoriasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAuditoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdOperacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SevencWpf.ServicioWcf.DetalleAuditoria> DetallesAuditorias {
            get {
                return this.DetallesAuditoriasField;
            }
            set {
                if ((object.ReferenceEquals(this.DetallesAuditoriasField, value) != true)) {
                    this.DetallesAuditoriasField = value;
                    this.RaisePropertyChanged("DetallesAuditorias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAuditoria {
            get {
                return this.IdAuditoriaField;
            }
            set {
                if ((this.IdAuditoriaField.Equals(value) != true)) {
                    this.IdAuditoriaField = value;
                    this.RaisePropertyChanged("IdAuditoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdOperacion {
            get {
                return this.IdOperacionField;
            }
            set {
                if ((this.IdOperacionField.Equals(value) != true)) {
                    this.IdOperacionField = value;
                    this.RaisePropertyChanged("IdOperacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rol", Namespace="http://schemas.datacontract.org/2004/07/SEVENC.Dominio.Entidades", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Rol : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ConcurrenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstaActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstaEliminadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SevencWpf.ServicioWcf.Operacion> OperacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SevencWpf.ServicioWcf.Usuario> UsuariosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Concurrencia {
            get {
                return this.ConcurrenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ConcurrenciaField, value) != true)) {
                    this.ConcurrenciaField = value;
                    this.RaisePropertyChanged("Concurrencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsSistema {
            get {
                return this.EsSistemaField;
            }
            set {
                if ((this.EsSistemaField.Equals(value) != true)) {
                    this.EsSistemaField = value;
                    this.RaisePropertyChanged("EsSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstaActivo {
            get {
                return this.EstaActivoField;
            }
            set {
                if ((this.EstaActivoField.Equals(value) != true)) {
                    this.EstaActivoField = value;
                    this.RaisePropertyChanged("EstaActivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstaEliminado {
            get {
                return this.EstaEliminadoField;
            }
            set {
                if ((this.EstaEliminadoField.Equals(value) != true)) {
                    this.EstaEliminadoField = value;
                    this.RaisePropertyChanged("EstaEliminado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRol {
            get {
                return this.IdRolField;
            }
            set {
                if ((this.IdRolField.Equals(value) != true)) {
                    this.IdRolField = value;
                    this.RaisePropertyChanged("IdRol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SevencWpf.ServicioWcf.Operacion> Operaciones {
            get {
                return this.OperacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.OperacionesField, value) != true)) {
                    this.OperacionesField = value;
                    this.RaisePropertyChanged("Operaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SevencWpf.ServicioWcf.Usuario> Usuarios {
            get {
                return this.UsuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuariosField, value) != true)) {
                    this.UsuariosField = value;
                    this.RaisePropertyChanged("Usuarios");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SesionUsuario", Namespace="http://schemas.datacontract.org/2004/07/SEVENC.Dominio.Entidades", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class SesionUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdSesionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((this.FechaFinField.Equals(value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdSesion {
            get {
                return this.IdSesionField;
            }
            set {
                if ((this.IdSesionField.Equals(value) != true)) {
                    this.IdSesionField = value;
                    this.RaisePropertyChanged("IdSesion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ip {
            get {
                return this.IpField;
            }
            set {
                if ((object.ReferenceEquals(this.IpField, value) != true)) {
                    this.IpField = value;
                    this.RaisePropertyChanged("Ip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleAuditoria", Namespace="http://schemas.datacontract.org/2004/07/SEVENC.Dominio.Entidades", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class DetalleAuditoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveEntidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAuditoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdDetalleAuditoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorAntiguoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValorNuevoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campo {
            get {
                return this.CampoField;
            }
            set {
                if ((object.ReferenceEquals(this.CampoField, value) != true)) {
                    this.CampoField = value;
                    this.RaisePropertyChanged("Campo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveEntidad {
            get {
                return this.ClaveEntidadField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveEntidadField, value) != true)) {
                    this.ClaveEntidadField = value;
                    this.RaisePropertyChanged("ClaveEntidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Entidad {
            get {
                return this.EntidadField;
            }
            set {
                if ((object.ReferenceEquals(this.EntidadField, value) != true)) {
                    this.EntidadField = value;
                    this.RaisePropertyChanged("Entidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAuditoria {
            get {
                return this.IdAuditoriaField;
            }
            set {
                if ((this.IdAuditoriaField.Equals(value) != true)) {
                    this.IdAuditoriaField = value;
                    this.RaisePropertyChanged("IdAuditoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdDetalleAuditoria {
            get {
                return this.IdDetalleAuditoriaField;
            }
            set {
                if ((this.IdDetalleAuditoriaField.Equals(value) != true)) {
                    this.IdDetalleAuditoriaField = value;
                    this.RaisePropertyChanged("IdDetalleAuditoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValorAntiguo {
            get {
                return this.ValorAntiguoField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorAntiguoField, value) != true)) {
                    this.ValorAntiguoField = value;
                    this.RaisePropertyChanged("ValorAntiguo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValorNuevo {
            get {
                return this.ValorNuevoField;
            }
            set {
                if ((object.ReferenceEquals(this.ValorNuevoField, value) != true)) {
                    this.ValorNuevoField = value;
                    this.RaisePropertyChanged("ValorNuevo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operacion", Namespace="http://schemas.datacontract.org/2004/07/SEVENC.Dominio.Entidades", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Operacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SevencWpf.ServicioWcf.Auditoria> AuditoriasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsAuditableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstaActivaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdOperacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SevencWpf.ServicioWcf.Rol> RolesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SevencWpf.ServicioWcf.Auditoria> Auditorias {
            get {
                return this.AuditoriasField;
            }
            set {
                if ((object.ReferenceEquals(this.AuditoriasField, value) != true)) {
                    this.AuditoriasField = value;
                    this.RaisePropertyChanged("Auditorias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsAuditable {
            get {
                return this.EsAuditableField;
            }
            set {
                if ((this.EsAuditableField.Equals(value) != true)) {
                    this.EsAuditableField = value;
                    this.RaisePropertyChanged("EsAuditable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstaActiva {
            get {
                return this.EstaActivaField;
            }
            set {
                if ((this.EstaActivaField.Equals(value) != true)) {
                    this.EstaActivaField = value;
                    this.RaisePropertyChanged("EstaActiva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdOperacion {
            get {
                return this.IdOperacionField;
            }
            set {
                if ((this.IdOperacionField.Equals(value) != true)) {
                    this.IdOperacionField = value;
                    this.RaisePropertyChanged("IdOperacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SevencWpf.ServicioWcf.Rol> Roles {
            get {
                return this.RolesField;
            }
            set {
                if ((object.ReferenceEquals(this.RolesField, value) != true)) {
                    this.RolesField = value;
                    this.RaisePropertyChanged("Roles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/SEVENC.Dominio.Entidades", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detalle {
            get {
                return this.DetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleField, value) != true)) {
                    this.DetalleField = value;
                    this.RaisePropertyChanged("Detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdError {
            get {
                return this.IdErrorField;
            }
            set {
                if ((this.IdErrorField.Equals(value) != true)) {
                    this.IdErrorField = value;
                    this.RaisePropertyChanged("IdError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Busqueda", Namespace="http://schemas.datacontract.org/2004/07/SEVENC.Aplicacion.Aplicacion.Interfaces.M" +
        "odulo_Seguridad")]
    public enum Busqueda : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PorId = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PorUserName = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PorEmail = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PorNombresApellidos = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginData", Namespace="http://schemas.datacontract.org/2004/07/SEVENC.Aplicacion.Aplicacion.Contratos.Mo" +
        "dulo_Seguridad")]
    [System.SerializableAttribute()]
    public partial class LoginData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SevencWpf.ServicioWcf.Empresa EmpresaSeleccionadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SevencWpf.ServicioWcf.Empresa> EmpresasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FueOkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdSesionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, bool> OperacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SevencWpf.ServicioWcf.Empresa EmpresaSeleccionada {
            get {
                return this.EmpresaSeleccionadaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaSeleccionadaField, value) != true)) {
                    this.EmpresaSeleccionadaField = value;
                    this.RaisePropertyChanged("EmpresaSeleccionada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SevencWpf.ServicioWcf.Empresa> Empresas {
            get {
                return this.EmpresasField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresasField, value) != true)) {
                    this.EmpresasField = value;
                    this.RaisePropertyChanged("Empresas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FueOk {
            get {
                return this.FueOkField;
            }
            set {
                if ((this.FueOkField.Equals(value) != true)) {
                    this.FueOkField = value;
                    this.RaisePropertyChanged("FueOk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdSesion {
            get {
                return this.IdSesionField;
            }
            set {
                if ((this.IdSesionField.Equals(value) != true)) {
                    this.IdSesionField = value;
                    this.RaisePropertyChanged("IdSesion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, bool> Operaciones {
            get {
                return this.OperacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.OperacionesField, value) != true)) {
                    this.OperacionesField = value;
                    this.RaisePropertyChanged("Operaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioWcf.IServicioWcf")]
    public interface IServicioWcf {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/ObtenerEmpresas", ReplyAction="http://tempuri.org/IEmpresa/ObtenerEmpresasResponse")]
        System.Collections.Generic.List<SevencWpf.ServicioWcf.Empresa> ObtenerEmpresas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/ObtenerEmpresas", ReplyAction="http://tempuri.org/IEmpresa/ObtenerEmpresasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SevencWpf.ServicioWcf.Empresa>> ObtenerEmpresasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/CrearEmpresa", ReplyAction="http://tempuri.org/IEmpresa/CrearEmpresaResponse")]
        void CrearEmpresa(SevencWpf.ServicioWcf.Empresa empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/CrearEmpresa", ReplyAction="http://tempuri.org/IEmpresa/CrearEmpresaResponse")]
        System.Threading.Tasks.Task CrearEmpresaAsync(SevencWpf.ServicioWcf.Empresa empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/ActualizarEmpresa", ReplyAction="http://tempuri.org/IEmpresa/ActualizarEmpresaResponse")]
        void ActualizarEmpresa(SevencWpf.ServicioWcf.Empresa empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/ActualizarEmpresa", ReplyAction="http://tempuri.org/IEmpresa/ActualizarEmpresaResponse")]
        System.Threading.Tasks.Task ActualizarEmpresaAsync(SevencWpf.ServicioWcf.Empresa empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/ObtenerSucursalesPorIdEmpresa", ReplyAction="http://tempuri.org/IEmpresa/ObtenerSucursalesPorIdEmpresaResponse")]
        System.Collections.Generic.List<SevencWpf.ServicioWcf.Sucursal> ObtenerSucursalesPorIdEmpresa(byte idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/ObtenerSucursalesPorIdEmpresa", ReplyAction="http://tempuri.org/IEmpresa/ObtenerSucursalesPorIdEmpresaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SevencWpf.ServicioWcf.Sucursal>> ObtenerSucursalesPorIdEmpresaAsync(byte idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/ObtenerUsuariosPorIdEmpresa", ReplyAction="http://tempuri.org/IEmpresa/ObtenerUsuariosPorIdEmpresaResponse")]
        System.Collections.Generic.List<SevencWpf.ServicioWcf.Usuario> ObtenerUsuariosPorIdEmpresa(byte idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/ObtenerUsuariosPorIdEmpresa", ReplyAction="http://tempuri.org/IEmpresa/ObtenerUsuariosPorIdEmpresaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SevencWpf.ServicioWcf.Usuario>> ObtenerUsuariosPorIdEmpresaAsync(byte idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/AsignarSucursalesAEmpresa", ReplyAction="http://tempuri.org/IEmpresa/AsignarSucursalesAEmpresaResponse")]
        void AsignarSucursalesAEmpresa(System.Collections.Generic.List<short> idsSucursales, byte idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/AsignarSucursalesAEmpresa", ReplyAction="http://tempuri.org/IEmpresa/AsignarSucursalesAEmpresaResponse")]
        System.Threading.Tasks.Task AsignarSucursalesAEmpresaAsync(System.Collections.Generic.List<short> idsSucursales, byte idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/AsignarUsuariosAEmpresa", ReplyAction="http://tempuri.org/IEmpresa/AsignarUsuariosAEmpresaResponse")]
        void AsignarUsuariosAEmpresa(System.Collections.Generic.List<int> idsUsuarios, byte idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresa/AsignarUsuariosAEmpresa", ReplyAction="http://tempuri.org/IEmpresa/AsignarUsuariosAEmpresaResponse")]
        System.Threading.Tasks.Task AsignarUsuariosAEmpresaAsync(System.Collections.Generic.List<int> idsUsuarios, byte idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IError/CrearError", ReplyAction="http://tempuri.org/IError/CrearErrorResponse")]
        int CrearError(SevencWpf.ServicioWcf.Error error);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IError/CrearError", ReplyAction="http://tempuri.org/IError/CrearErrorResponse")]
        System.Threading.Tasks.Task<int> CrearErrorAsync(SevencWpf.ServicioWcf.Error error);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISucursal/ObtenerSucursales", ReplyAction="http://tempuri.org/ISucursal/ObtenerSucursalesResponse")]
        System.Collections.Generic.List<SevencWpf.ServicioWcf.Sucursal> ObtenerSucursales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISucursal/ObtenerSucursales", ReplyAction="http://tempuri.org/ISucursal/ObtenerSucursalesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SevencWpf.ServicioWcf.Sucursal>> ObtenerSucursalesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISucursal/CrearSucursal", ReplyAction="http://tempuri.org/ISucursal/CrearSucursalResponse")]
        void CrearSucursal(SevencWpf.ServicioWcf.Sucursal sucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISucursal/CrearSucursal", ReplyAction="http://tempuri.org/ISucursal/CrearSucursalResponse")]
        System.Threading.Tasks.Task CrearSucursalAsync(SevencWpf.ServicioWcf.Sucursal sucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISucursal/ActualizarSucursal", ReplyAction="http://tempuri.org/ISucursal/ActualizarSucursalResponse")]
        void ActualizarSucursal(SevencWpf.ServicioWcf.Sucursal sucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISucursal/ActualizarSucursal", ReplyAction="http://tempuri.org/ISucursal/ActualizarSucursalResponse")]
        System.Threading.Tasks.Task ActualizarSucursalAsync(SevencWpf.ServicioWcf.Sucursal sucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/ObtenerUsuarios", ReplyAction="http://tempuri.org/IUsuario/ObtenerUsuariosResponse")]
        System.Collections.Generic.List<SevencWpf.ServicioWcf.Usuario> ObtenerUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/ObtenerUsuarios", ReplyAction="http://tempuri.org/IUsuario/ObtenerUsuariosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SevencWpf.ServicioWcf.Usuario>> ObtenerUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/ObtenerUsuariosPorCriteriosBusqueda", ReplyAction="http://tempuri.org/IUsuario/ObtenerUsuariosPorCriteriosBusquedaResponse")]
        System.Collections.Generic.List<SevencWpf.ServicioWcf.Usuario> ObtenerUsuariosPorCriteriosBusqueda(System.Collections.Generic.Dictionary<SevencWpf.ServicioWcf.Busqueda, string> criteriosBusqueda, int indicePagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/ObtenerUsuariosPorCriteriosBusqueda", ReplyAction="http://tempuri.org/IUsuario/ObtenerUsuariosPorCriteriosBusquedaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SevencWpf.ServicioWcf.Usuario>> ObtenerUsuariosPorCriteriosBusquedaAsync(System.Collections.Generic.Dictionary<SevencWpf.ServicioWcf.Busqueda, string> criteriosBusqueda, int indicePagina);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/ObtenerRolesPorIdUsuario", ReplyAction="http://tempuri.org/IUsuario/ObtenerRolesPorIdUsuarioResponse")]
        System.Collections.Generic.List<SevencWpf.ServicioWcf.Rol> ObtenerRolesPorIdUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/ObtenerRolesPorIdUsuario", ReplyAction="http://tempuri.org/IUsuario/ObtenerRolesPorIdUsuarioResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SevencWpf.ServicioWcf.Rol>> ObtenerRolesPorIdUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/CrearUsuario", ReplyAction="http://tempuri.org/IUsuario/CrearUsuarioResponse")]
        void CrearUsuario(SevencWpf.ServicioWcf.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/CrearUsuario", ReplyAction="http://tempuri.org/IUsuario/CrearUsuarioResponse")]
        System.Threading.Tasks.Task CrearUsuarioAsync(SevencWpf.ServicioWcf.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/ActualizarUsuario", ReplyAction="http://tempuri.org/IUsuario/ActualizarUsuarioResponse")]
        void ActualizarUsuario(SevencWpf.ServicioWcf.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/ActualizarUsuario", ReplyAction="http://tempuri.org/IUsuario/ActualizarUsuarioResponse")]
        System.Threading.Tasks.Task ActualizarUsuarioAsync(SevencWpf.ServicioWcf.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/CambiarContrasena", ReplyAction="http://tempuri.org/IUsuario/CambiarContrasenaResponse")]
        void CambiarContrasena(int idUsuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/CambiarContrasena", ReplyAction="http://tempuri.org/IUsuario/CambiarContrasenaResponse")]
        System.Threading.Tasks.Task CambiarContrasenaAsync(int idUsuario, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/GenerarContrasena", ReplyAction="http://tempuri.org/IUsuario/GenerarContrasenaResponse")]
        void GenerarContrasena(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/GenerarContrasena", ReplyAction="http://tempuri.org/IUsuario/GenerarContrasenaResponse")]
        System.Threading.Tasks.Task GenerarContrasenaAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/ExisteUserName", ReplyAction="http://tempuri.org/IUsuario/ExisteUserNameResponse")]
        bool ExisteUserName(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/ExisteUserName", ReplyAction="http://tempuri.org/IUsuario/ExisteUserNameResponse")]
        System.Threading.Tasks.Task<bool> ExisteUserNameAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/ExisteEmail", ReplyAction="http://tempuri.org/IUsuario/ExisteEmailResponse")]
        bool ExisteEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/ExisteEmail", ReplyAction="http://tempuri.org/IUsuario/ExisteEmailResponse")]
        System.Threading.Tasks.Task<bool> ExisteEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/AsignarRolesAUsuario", ReplyAction="http://tempuri.org/IUsuario/AsignarRolesAUsuarioResponse")]
        void AsignarRolesAUsuario(System.Collections.Generic.List<int> idsRoles, int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/AsignarRolesAUsuario", ReplyAction="http://tempuri.org/IUsuario/AsignarRolesAUsuarioResponse")]
        System.Threading.Tasks.Task AsignarRolesAUsuarioAsync(System.Collections.Generic.List<int> idsRoles, int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Login", ReplyAction="http://tempuri.org/IUsuario/LoginResponse")]
        SevencWpf.ServicioWcf.LoginData Login(string userName, string contrasena, string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/Login", ReplyAction="http://tempuri.org/IUsuario/LoginResponse")]
        System.Threading.Tasks.Task<SevencWpf.ServicioWcf.LoginData> LoginAsync(string userName, string contrasena, string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/CerrarSesion", ReplyAction="http://tempuri.org/IUsuario/CerrarSesionResponse")]
        void CerrarSesion(long idSesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuario/CerrarSesion", ReplyAction="http://tempuri.org/IUsuario/CerrarSesionResponse")]
        System.Threading.Tasks.Task CerrarSesionAsync(long idSesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRol/ObtenerRoles", ReplyAction="http://tempuri.org/IRol/ObtenerRolesResponse")]
        System.Collections.Generic.List<SevencWpf.ServicioWcf.Rol> ObtenerRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRol/ObtenerRoles", ReplyAction="http://tempuri.org/IRol/ObtenerRolesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SevencWpf.ServicioWcf.Rol>> ObtenerRolesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRol/ObtenerOperacionesPorIdRol", ReplyAction="http://tempuri.org/IRol/ObtenerOperacionesPorIdRolResponse")]
        System.Collections.Generic.List<SevencWpf.ServicioWcf.Operacion> ObtenerOperacionesPorIdRol(int idRol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRol/ObtenerOperacionesPorIdRol", ReplyAction="http://tempuri.org/IRol/ObtenerOperacionesPorIdRolResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SevencWpf.ServicioWcf.Operacion>> ObtenerOperacionesPorIdRolAsync(int idRol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRol/CrearRol", ReplyAction="http://tempuri.org/IRol/CrearRolResponse")]
        void CrearRol(SevencWpf.ServicioWcf.Rol rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRol/CrearRol", ReplyAction="http://tempuri.org/IRol/CrearRolResponse")]
        System.Threading.Tasks.Task CrearRolAsync(SevencWpf.ServicioWcf.Rol rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRol/ActualizarRol", ReplyAction="http://tempuri.org/IRol/ActualizarRolResponse")]
        void ActualizarRol(SevencWpf.ServicioWcf.Rol rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRol/ActualizarRol", ReplyAction="http://tempuri.org/IRol/ActualizarRolResponse")]
        System.Threading.Tasks.Task ActualizarRolAsync(SevencWpf.ServicioWcf.Rol rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRol/AsignarOperacionesARol", ReplyAction="http://tempuri.org/IRol/AsignarOperacionesARolResponse")]
        void AsignarOperacionesARol(System.Collections.Generic.List<int> idsOperaciones, int idRol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRol/AsignarOperacionesARol", ReplyAction="http://tempuri.org/IRol/AsignarOperacionesARolResponse")]
        System.Threading.Tasks.Task AsignarOperacionesARolAsync(System.Collections.Generic.List<int> idsOperaciones, int idRol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacion/ObtenerOperaciones", ReplyAction="http://tempuri.org/IOperacion/ObtenerOperacionesResponse")]
        System.Collections.Generic.List<SevencWpf.ServicioWcf.Operacion> ObtenerOperaciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacion/ObtenerOperaciones", ReplyAction="http://tempuri.org/IOperacion/ObtenerOperacionesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<SevencWpf.ServicioWcf.Operacion>> ObtenerOperacionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacion/ActualizarOperacion", ReplyAction="http://tempuri.org/IOperacion/ActualizarOperacionResponse")]
        void ActualizarOperacion(SevencWpf.ServicioWcf.Operacion operacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperacion/ActualizarOperacion", ReplyAction="http://tempuri.org/IOperacion/ActualizarOperacionResponse")]
        System.Threading.Tasks.Task ActualizarOperacionAsync(SevencWpf.ServicioWcf.Operacion operacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuditoria/CrearAuditoria", ReplyAction="http://tempuri.org/IAuditoria/CrearAuditoriaResponse")]
        void CrearAuditoria(SevencWpf.ServicioWcf.Auditoria auditoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuditoria/CrearAuditoria", ReplyAction="http://tempuri.org/IAuditoria/CrearAuditoriaResponse")]
        System.Threading.Tasks.Task CrearAuditoriaAsync(SevencWpf.ServicioWcf.Auditoria auditoria);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioWcfChannel : SevencWpf.ServicioWcf.IServicioWcf, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWcfClient : System.ServiceModel.ClientBase<SevencWpf.ServicioWcf.IServicioWcf>, SevencWpf.ServicioWcf.IServicioWcf {
        
        public ServicioWcfClient() {
        }
        
        public ServicioWcfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWcfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWcfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWcfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<SevencWpf.ServicioWcf.Empresa> ObtenerEmpresas() {
            return base.Channel.ObtenerEmpresas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SevencWpf.ServicioWcf.Empresa>> ObtenerEmpresasAsync() {
            return base.Channel.ObtenerEmpresasAsync();
        }
        
        public void CrearEmpresa(SevencWpf.ServicioWcf.Empresa empresa) {
            base.Channel.CrearEmpresa(empresa);
        }
        
        public System.Threading.Tasks.Task CrearEmpresaAsync(SevencWpf.ServicioWcf.Empresa empresa) {
            return base.Channel.CrearEmpresaAsync(empresa);
        }
        
        public void ActualizarEmpresa(SevencWpf.ServicioWcf.Empresa empresa) {
            base.Channel.ActualizarEmpresa(empresa);
        }
        
        public System.Threading.Tasks.Task ActualizarEmpresaAsync(SevencWpf.ServicioWcf.Empresa empresa) {
            return base.Channel.ActualizarEmpresaAsync(empresa);
        }
        
        public System.Collections.Generic.List<SevencWpf.ServicioWcf.Sucursal> ObtenerSucursalesPorIdEmpresa(byte idEmpresa) {
            return base.Channel.ObtenerSucursalesPorIdEmpresa(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SevencWpf.ServicioWcf.Sucursal>> ObtenerSucursalesPorIdEmpresaAsync(byte idEmpresa) {
            return base.Channel.ObtenerSucursalesPorIdEmpresaAsync(idEmpresa);
        }
        
        public System.Collections.Generic.List<SevencWpf.ServicioWcf.Usuario> ObtenerUsuariosPorIdEmpresa(byte idEmpresa) {
            return base.Channel.ObtenerUsuariosPorIdEmpresa(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SevencWpf.ServicioWcf.Usuario>> ObtenerUsuariosPorIdEmpresaAsync(byte idEmpresa) {
            return base.Channel.ObtenerUsuariosPorIdEmpresaAsync(idEmpresa);
        }
        
        public void AsignarSucursalesAEmpresa(System.Collections.Generic.List<short> idsSucursales, byte idEmpresa) {
            base.Channel.AsignarSucursalesAEmpresa(idsSucursales, idEmpresa);
        }
        
        public System.Threading.Tasks.Task AsignarSucursalesAEmpresaAsync(System.Collections.Generic.List<short> idsSucursales, byte idEmpresa) {
            return base.Channel.AsignarSucursalesAEmpresaAsync(idsSucursales, idEmpresa);
        }
        
        public void AsignarUsuariosAEmpresa(System.Collections.Generic.List<int> idsUsuarios, byte idEmpresa) {
            base.Channel.AsignarUsuariosAEmpresa(idsUsuarios, idEmpresa);
        }
        
        public System.Threading.Tasks.Task AsignarUsuariosAEmpresaAsync(System.Collections.Generic.List<int> idsUsuarios, byte idEmpresa) {
            return base.Channel.AsignarUsuariosAEmpresaAsync(idsUsuarios, idEmpresa);
        }
        
        public int CrearError(SevencWpf.ServicioWcf.Error error) {
            return base.Channel.CrearError(error);
        }
        
        public System.Threading.Tasks.Task<int> CrearErrorAsync(SevencWpf.ServicioWcf.Error error) {
            return base.Channel.CrearErrorAsync(error);
        }
        
        public System.Collections.Generic.List<SevencWpf.ServicioWcf.Sucursal> ObtenerSucursales() {
            return base.Channel.ObtenerSucursales();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SevencWpf.ServicioWcf.Sucursal>> ObtenerSucursalesAsync() {
            return base.Channel.ObtenerSucursalesAsync();
        }
        
        public void CrearSucursal(SevencWpf.ServicioWcf.Sucursal sucursal) {
            base.Channel.CrearSucursal(sucursal);
        }
        
        public System.Threading.Tasks.Task CrearSucursalAsync(SevencWpf.ServicioWcf.Sucursal sucursal) {
            return base.Channel.CrearSucursalAsync(sucursal);
        }
        
        public void ActualizarSucursal(SevencWpf.ServicioWcf.Sucursal sucursal) {
            base.Channel.ActualizarSucursal(sucursal);
        }
        
        public System.Threading.Tasks.Task ActualizarSucursalAsync(SevencWpf.ServicioWcf.Sucursal sucursal) {
            return base.Channel.ActualizarSucursalAsync(sucursal);
        }
        
        public System.Collections.Generic.List<SevencWpf.ServicioWcf.Usuario> ObtenerUsuarios() {
            return base.Channel.ObtenerUsuarios();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SevencWpf.ServicioWcf.Usuario>> ObtenerUsuariosAsync() {
            return base.Channel.ObtenerUsuariosAsync();
        }
        
        public System.Collections.Generic.List<SevencWpf.ServicioWcf.Usuario> ObtenerUsuariosPorCriteriosBusqueda(System.Collections.Generic.Dictionary<SevencWpf.ServicioWcf.Busqueda, string> criteriosBusqueda, int indicePagina) {
            return base.Channel.ObtenerUsuariosPorCriteriosBusqueda(criteriosBusqueda, indicePagina);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SevencWpf.ServicioWcf.Usuario>> ObtenerUsuariosPorCriteriosBusquedaAsync(System.Collections.Generic.Dictionary<SevencWpf.ServicioWcf.Busqueda, string> criteriosBusqueda, int indicePagina) {
            return base.Channel.ObtenerUsuariosPorCriteriosBusquedaAsync(criteriosBusqueda, indicePagina);
        }
        
        public System.Collections.Generic.List<SevencWpf.ServicioWcf.Rol> ObtenerRolesPorIdUsuario(int idUsuario) {
            return base.Channel.ObtenerRolesPorIdUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SevencWpf.ServicioWcf.Rol>> ObtenerRolesPorIdUsuarioAsync(int idUsuario) {
            return base.Channel.ObtenerRolesPorIdUsuarioAsync(idUsuario);
        }
        
        public void CrearUsuario(SevencWpf.ServicioWcf.Usuario usuario) {
            base.Channel.CrearUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task CrearUsuarioAsync(SevencWpf.ServicioWcf.Usuario usuario) {
            return base.Channel.CrearUsuarioAsync(usuario);
        }
        
        public void ActualizarUsuario(SevencWpf.ServicioWcf.Usuario usuario) {
            base.Channel.ActualizarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task ActualizarUsuarioAsync(SevencWpf.ServicioWcf.Usuario usuario) {
            return base.Channel.ActualizarUsuarioAsync(usuario);
        }
        
        public void CambiarContrasena(int idUsuario, string contrasena) {
            base.Channel.CambiarContrasena(idUsuario, contrasena);
        }
        
        public System.Threading.Tasks.Task CambiarContrasenaAsync(int idUsuario, string contrasena) {
            return base.Channel.CambiarContrasenaAsync(idUsuario, contrasena);
        }
        
        public void GenerarContrasena(int idUsuario) {
            base.Channel.GenerarContrasena(idUsuario);
        }
        
        public System.Threading.Tasks.Task GenerarContrasenaAsync(int idUsuario) {
            return base.Channel.GenerarContrasenaAsync(idUsuario);
        }
        
        public bool ExisteUserName(string userName) {
            return base.Channel.ExisteUserName(userName);
        }
        
        public System.Threading.Tasks.Task<bool> ExisteUserNameAsync(string userName) {
            return base.Channel.ExisteUserNameAsync(userName);
        }
        
        public bool ExisteEmail(string email) {
            return base.Channel.ExisteEmail(email);
        }
        
        public System.Threading.Tasks.Task<bool> ExisteEmailAsync(string email) {
            return base.Channel.ExisteEmailAsync(email);
        }
        
        public void AsignarRolesAUsuario(System.Collections.Generic.List<int> idsRoles, int idUsuario) {
            base.Channel.AsignarRolesAUsuario(idsRoles, idUsuario);
        }
        
        public System.Threading.Tasks.Task AsignarRolesAUsuarioAsync(System.Collections.Generic.List<int> idsRoles, int idUsuario) {
            return base.Channel.AsignarRolesAUsuarioAsync(idsRoles, idUsuario);
        }
        
        public SevencWpf.ServicioWcf.LoginData Login(string userName, string contrasena, string ip) {
            return base.Channel.Login(userName, contrasena, ip);
        }
        
        public System.Threading.Tasks.Task<SevencWpf.ServicioWcf.LoginData> LoginAsync(string userName, string contrasena, string ip) {
            return base.Channel.LoginAsync(userName, contrasena, ip);
        }
        
        public void CerrarSesion(long idSesion) {
            base.Channel.CerrarSesion(idSesion);
        }
        
        public System.Threading.Tasks.Task CerrarSesionAsync(long idSesion) {
            return base.Channel.CerrarSesionAsync(idSesion);
        }
        
        public System.Collections.Generic.List<SevencWpf.ServicioWcf.Rol> ObtenerRoles() {
            return base.Channel.ObtenerRoles();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SevencWpf.ServicioWcf.Rol>> ObtenerRolesAsync() {
            return base.Channel.ObtenerRolesAsync();
        }
        
        public System.Collections.Generic.List<SevencWpf.ServicioWcf.Operacion> ObtenerOperacionesPorIdRol(int idRol) {
            return base.Channel.ObtenerOperacionesPorIdRol(idRol);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SevencWpf.ServicioWcf.Operacion>> ObtenerOperacionesPorIdRolAsync(int idRol) {
            return base.Channel.ObtenerOperacionesPorIdRolAsync(idRol);
        }
        
        public void CrearRol(SevencWpf.ServicioWcf.Rol rol) {
            base.Channel.CrearRol(rol);
        }
        
        public System.Threading.Tasks.Task CrearRolAsync(SevencWpf.ServicioWcf.Rol rol) {
            return base.Channel.CrearRolAsync(rol);
        }
        
        public void ActualizarRol(SevencWpf.ServicioWcf.Rol rol) {
            base.Channel.ActualizarRol(rol);
        }
        
        public System.Threading.Tasks.Task ActualizarRolAsync(SevencWpf.ServicioWcf.Rol rol) {
            return base.Channel.ActualizarRolAsync(rol);
        }
        
        public void AsignarOperacionesARol(System.Collections.Generic.List<int> idsOperaciones, int idRol) {
            base.Channel.AsignarOperacionesARol(idsOperaciones, idRol);
        }
        
        public System.Threading.Tasks.Task AsignarOperacionesARolAsync(System.Collections.Generic.List<int> idsOperaciones, int idRol) {
            return base.Channel.AsignarOperacionesARolAsync(idsOperaciones, idRol);
        }
        
        public System.Collections.Generic.List<SevencWpf.ServicioWcf.Operacion> ObtenerOperaciones() {
            return base.Channel.ObtenerOperaciones();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<SevencWpf.ServicioWcf.Operacion>> ObtenerOperacionesAsync() {
            return base.Channel.ObtenerOperacionesAsync();
        }
        
        public void ActualizarOperacion(SevencWpf.ServicioWcf.Operacion operacion) {
            base.Channel.ActualizarOperacion(operacion);
        }
        
        public System.Threading.Tasks.Task ActualizarOperacionAsync(SevencWpf.ServicioWcf.Operacion operacion) {
            return base.Channel.ActualizarOperacionAsync(operacion);
        }
        
        public void CrearAuditoria(SevencWpf.ServicioWcf.Auditoria auditoria) {
            base.Channel.CrearAuditoria(auditoria);
        }
        
        public System.Threading.Tasks.Task CrearAuditoriaAsync(SevencWpf.ServicioWcf.Auditoria auditoria) {
            return base.Channel.CrearAuditoriaAsync(auditoria);
        }
    }
}
