
-- --------------------------------------------------
-- Entity Designer DDL Script for SQL Server 2005, 2008, 2012 and Azure
-- --------------------------------------------------
-- Date Created: 03/04/2019 09:45:31
-- Generated from EDMX file: C:\Proyectos\PROASOFT\SqlEntityFramework\Modelo\ModeloProasoft.edmx
-- --------------------------------------------------

SET QUOTED_IDENTIFIER OFF;
GO
USE [BDPROASOFT];
GO
IF SCHEMA_ID(N'dbo') IS NULL EXECUTE(N'CREATE SCHEMA [dbo]');
GO

-- --------------------------------------------------
-- Dropping existing FOREIGN KEY constraints
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[FK_DETALLE_COMPRAITEM]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[DETALLES_COMPRAS] DROP CONSTRAINT [FK_DETALLE_COMPRAITEM];
GO
IF OBJECT_ID(N'[dbo].[FK_COMPRADETALLE_COMPRA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[DETALLES_COMPRAS] DROP CONSTRAINT [FK_COMPRADETALLE_COMPRA];
GO
IF OBJECT_ID(N'[dbo].[FK_RECETADETALLE_RECETA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[DETALLES_RECETAS] DROP CONSTRAINT [FK_RECETADETALLE_RECETA];
GO
IF OBJECT_ID(N'[dbo].[FK_DETALLE_RECETAITEM]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[DETALLES_RECETAS] DROP CONSTRAINT [FK_DETALLE_RECETAITEM];
GO
IF OBJECT_ID(N'[dbo].[FK_ROLUSUARIO_ROL]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ROLUSUARIO] DROP CONSTRAINT [FK_ROLUSUARIO_ROL];
GO
IF OBJECT_ID(N'[dbo].[FK_ROLUSUARIO_USUARIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ROLUSUARIO] DROP CONSTRAINT [FK_ROLUSUARIO_USUARIO];
GO
IF OBJECT_ID(N'[dbo].[FK_COMPRAUSUARIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[COMPRAS] DROP CONSTRAINT [FK_COMPRAUSUARIO];
GO
IF OBJECT_ID(N'[dbo].[FK_PRODUCCIONDETALLE_PRODUCCION]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[DETALLES_PRODUCCIONES] DROP CONSTRAINT [FK_PRODUCCIONDETALLE_PRODUCCION];
GO
IF OBJECT_ID(N'[dbo].[FK_RECETADETALLE_PRODUCCION]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[DETALLES_PRODUCCIONES] DROP CONSTRAINT [FK_RECETADETALLE_PRODUCCION];
GO
IF OBJECT_ID(N'[dbo].[FK_PRODUCCIONUSUARIO]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[PRODUCCIONES] DROP CONSTRAINT [FK_PRODUCCIONUSUARIO];
GO
IF OBJECT_ID(N'[dbo].[FK_ITEMMEDIDA]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[ITEMS] DROP CONSTRAINT [FK_ITEMMEDIDA];
GO
IF OBJECT_ID(N'[dbo].[FK_ITEMSTOCK_PRODUCCION]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[STOCK_PRODUCCION] DROP CONSTRAINT [FK_ITEMSTOCK_PRODUCCION];
GO
IF OBJECT_ID(N'[dbo].[FK_COMPRAPROVEEDOR]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[COMPRAS] DROP CONSTRAINT [FK_COMPRAPROVEEDOR];
GO
IF OBJECT_ID(N'[dbo].[FK_ITEMSTOCK_BODEGA_PRINCIPAL]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[STOCK_BODEGA_PRINCIPAL] DROP CONSTRAINT [FK_ITEMSTOCK_BODEGA_PRINCIPAL];
GO
IF OBJECT_ID(N'[dbo].[FK_EMPLEADODETALLE_PRODUCCION]', 'F') IS NOT NULL
    ALTER TABLE [dbo].[DETALLES_PRODUCCIONES] DROP CONSTRAINT [FK_EMPLEADODETALLE_PRODUCCION];
GO

-- --------------------------------------------------
-- Dropping existing tables
-- --------------------------------------------------

IF OBJECT_ID(N'[dbo].[ITEMS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[ITEMS];
GO
IF OBJECT_ID(N'[dbo].[COMPRAS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[COMPRAS];
GO
IF OBJECT_ID(N'[dbo].[DETALLES_COMPRAS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[DETALLES_COMPRAS];
GO
IF OBJECT_ID(N'[dbo].[RECETAS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[RECETAS];
GO
IF OBJECT_ID(N'[dbo].[DETALLES_RECETAS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[DETALLES_RECETAS];
GO
IF OBJECT_ID(N'[dbo].[USUARIOS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[USUARIOS];
GO
IF OBJECT_ID(N'[dbo].[ROLES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[ROLES];
GO
IF OBJECT_ID(N'[dbo].[PRODUCCIONES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PRODUCCIONES];
GO
IF OBJECT_ID(N'[dbo].[DETALLES_PRODUCCIONES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[DETALLES_PRODUCCIONES];
GO
IF OBJECT_ID(N'[dbo].[MEDIDAS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[MEDIDAS];
GO
IF OBJECT_ID(N'[dbo].[STOCK_PRODUCCION]', 'U') IS NOT NULL
    DROP TABLE [dbo].[STOCK_PRODUCCION];
GO
IF OBJECT_ID(N'[dbo].[PROVEEDORES]', 'U') IS NOT NULL
    DROP TABLE [dbo].[PROVEEDORES];
GO
IF OBJECT_ID(N'[dbo].[EMPLEADOS]', 'U') IS NOT NULL
    DROP TABLE [dbo].[EMPLEADOS];
GO
IF OBJECT_ID(N'[dbo].[STOCK_BODEGA_PRINCIPAL]', 'U') IS NOT NULL
    DROP TABLE [dbo].[STOCK_BODEGA_PRINCIPAL];
GO
IF OBJECT_ID(N'[dbo].[ROLUSUARIO]', 'U') IS NOT NULL
    DROP TABLE [dbo].[ROLUSUARIO];
GO

-- --------------------------------------------------
-- Creating all tables
-- --------------------------------------------------

-- Creating table 'ITEMS'
CREATE TABLE [dbo].[ITEMS] (
    [ID_ITEM] int IDENTITY(1,1) NOT NULL,
    [NOMBRE] nvarchar(100)  NOT NULL,
    [ESTA_ACTIVO] bit  NOT NULL,
    [ID_MEDIDA] tinyint  NOT NULL,
    [COSTO_POR_KILOGRAMO] decimal(18,4)  NOT NULL
);
GO

-- Creating table 'COMPRAS'
CREATE TABLE [dbo].[COMPRAS] (
    [ID_COMPRA] int IDENTITY(1,1) NOT NULL,
    [FECHA] datetime  NOT NULL,
    [ID_USUARIO] smallint  NOT NULL,
    [ESTA_CONFIRMADA] bit  NOT NULL,
    [ID_PROVEEDOR] int  NOT NULL
);
GO

-- Creating table 'DETALLES_COMPRAS'
CREATE TABLE [dbo].[DETALLES_COMPRAS] (
    [ID_DETALLE] bigint IDENTITY(1,1) NOT NULL,
    [CANTIDAD] smallint  NOT NULL,
    [PRECIO] decimal(18,4)  NOT NULL,
    [ID_ITEM] int  NOT NULL,
    [ID_COMPRA] int  NOT NULL
);
GO

-- Creating table 'RECETAS'
CREATE TABLE [dbo].[RECETAS] (
    [ID_RECETA] int IDENTITY(1,1) NOT NULL,
    [NOMBRE] nvarchar(200)  NOT NULL,
    [ESTA_ACTIVA] bit  NOT NULL
);
GO

-- Creating table 'DETALLES_RECETAS'
CREATE TABLE [dbo].[DETALLES_RECETAS] (
    [ID_DETALLE_RECETA] int IDENTITY(1,1) NOT NULL,
    [CANTIDAD] float  NOT NULL,
    [ID_RECETA] int  NOT NULL,
    [ID_ITEM] int  NOT NULL
);
GO

-- Creating table 'USUARIOS'
CREATE TABLE [dbo].[USUARIOS] (
    [ID_USUARIO] smallint IDENTITY(1,1) NOT NULL,
    [USER_NAME] nvarchar(30)  NOT NULL,
    [CONTRASENA] nvarchar(max)  NOT NULL,
    [ESTA_ACTIVO] bit  NOT NULL,
    [NOMBRES] nvarchar(100)  NOT NULL,
    [APELLIDOS] nvarchar(100)  NOT NULL
);
GO

-- Creating table 'ROLES'
CREATE TABLE [dbo].[ROLES] (
    [ID_ROL] smallint IDENTITY(1,1) NOT NULL,
    [NOMBRE] nvarchar(max)  NOT NULL,
    [ESTA_ACTIVO] nvarchar(max)  NOT NULL
);
GO

-- Creating table 'PRODUCCIONES'
CREATE TABLE [dbo].[PRODUCCIONES] (
    [ID_PRODUCCION] int IDENTITY(1,1) NOT NULL,
    [FECHA] datetime  NOT NULL,
    [ID_USUARIO] smallint  NOT NULL,
    [ES_REAL] bit  NOT NULL
);
GO

-- Creating table 'DETALLES_PRODUCCIONES'
CREATE TABLE [dbo].[DETALLES_PRODUCCIONES] (
    [ID] bigint IDENTITY(1,1) NOT NULL,
    [CANTIDAD] smallint  NOT NULL,
    [ID_PRODUCCION] int  NOT NULL,
    [ID_RECETA] int  NOT NULL,
    [ID_EMPLEADO] int  NOT NULL
);
GO

-- Creating table 'MEDIDAS'
CREATE TABLE [dbo].[MEDIDAS] (
    [ID_MEDIDA] tinyint IDENTITY(1,1) NOT NULL,
    [ETIQUETA] nvarchar(20)  NOT NULL,
    [VALOR] float  NOT NULL
);
GO

-- Creating table 'STOCK_PRODUCCION'
CREATE TABLE [dbo].[STOCK_PRODUCCION] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [CANTIDAD] float  NOT NULL,
    [CANTIDAD_ORDEN_PRODUCCION] float  NOT NULL,
    [ITEM_ID_ITEM] int  NOT NULL
);
GO

-- Creating table 'PROVEEDORES'
CREATE TABLE [dbo].[PROVEEDORES] (
    [ID_PROVEEDOR] int IDENTITY(1,1) NOT NULL,
    [RUC] nvarchar(15)  NOT NULL,
    [RAZON_SOCIAL] nvarchar(150)  NOT NULL,
    [ESTA_ACTIVO] bit  NOT NULL
);
GO

-- Creating table 'EMPLEADOS'
CREATE TABLE [dbo].[EMPLEADOS] (
    [ID_EMPLEADO] int IDENTITY(1,1) NOT NULL,
    [IDENTIFICACION] nvarchar(20)  NOT NULL,
    [NOMBRES] nvarchar(100)  NOT NULL,
    [APELLIDOS] nvarchar(100)  NOT NULL,
    [ESTA_ACTIVO] bit  NOT NULL
);
GO

-- Creating table 'STOCK_BODEGA_PRINCIPAL'
CREATE TABLE [dbo].[STOCK_BODEGA_PRINCIPAL] (
    [ID] int IDENTITY(1,1) NOT NULL,
    [CANTIDAD] float  NOT NULL,
    [ITEM_ID_ITEM] int  NOT NULL
);
GO

-- Creating table 'ROLUSUARIO'
CREATE TABLE [dbo].[ROLUSUARIO] (
    [ROLES_ID_ROL] smallint  NOT NULL,
    [USUARIOS_ID_USUARIO] smallint  NOT NULL
);
GO

-- --------------------------------------------------
-- Creating all PRIMARY KEY constraints
-- --------------------------------------------------

-- Creating primary key on [ID_ITEM] in table 'ITEMS'
ALTER TABLE [dbo].[ITEMS]
ADD CONSTRAINT [PK_ITEMS]
    PRIMARY KEY CLUSTERED ([ID_ITEM] ASC);
GO

-- Creating primary key on [ID_COMPRA] in table 'COMPRAS'
ALTER TABLE [dbo].[COMPRAS]
ADD CONSTRAINT [PK_COMPRAS]
    PRIMARY KEY CLUSTERED ([ID_COMPRA] ASC);
GO

-- Creating primary key on [ID_DETALLE] in table 'DETALLES_COMPRAS'
ALTER TABLE [dbo].[DETALLES_COMPRAS]
ADD CONSTRAINT [PK_DETALLES_COMPRAS]
    PRIMARY KEY CLUSTERED ([ID_DETALLE] ASC);
GO

-- Creating primary key on [ID_RECETA] in table 'RECETAS'
ALTER TABLE [dbo].[RECETAS]
ADD CONSTRAINT [PK_RECETAS]
    PRIMARY KEY CLUSTERED ([ID_RECETA] ASC);
GO

-- Creating primary key on [ID_DETALLE_RECETA] in table 'DETALLES_RECETAS'
ALTER TABLE [dbo].[DETALLES_RECETAS]
ADD CONSTRAINT [PK_DETALLES_RECETAS]
    PRIMARY KEY CLUSTERED ([ID_DETALLE_RECETA] ASC);
GO

-- Creating primary key on [ID_USUARIO] in table 'USUARIOS'
ALTER TABLE [dbo].[USUARIOS]
ADD CONSTRAINT [PK_USUARIOS]
    PRIMARY KEY CLUSTERED ([ID_USUARIO] ASC);
GO

-- Creating primary key on [ID_ROL] in table 'ROLES'
ALTER TABLE [dbo].[ROLES]
ADD CONSTRAINT [PK_ROLES]
    PRIMARY KEY CLUSTERED ([ID_ROL] ASC);
GO

-- Creating primary key on [ID_PRODUCCION] in table 'PRODUCCIONES'
ALTER TABLE [dbo].[PRODUCCIONES]
ADD CONSTRAINT [PK_PRODUCCIONES]
    PRIMARY KEY CLUSTERED ([ID_PRODUCCION] ASC);
GO

-- Creating primary key on [ID] in table 'DETALLES_PRODUCCIONES'
ALTER TABLE [dbo].[DETALLES_PRODUCCIONES]
ADD CONSTRAINT [PK_DETALLES_PRODUCCIONES]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID_MEDIDA] in table 'MEDIDAS'
ALTER TABLE [dbo].[MEDIDAS]
ADD CONSTRAINT [PK_MEDIDAS]
    PRIMARY KEY CLUSTERED ([ID_MEDIDA] ASC);
GO

-- Creating primary key on [ID] in table 'STOCK_PRODUCCION'
ALTER TABLE [dbo].[STOCK_PRODUCCION]
ADD CONSTRAINT [PK_STOCK_PRODUCCION]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ID_PROVEEDOR] in table 'PROVEEDORES'
ALTER TABLE [dbo].[PROVEEDORES]
ADD CONSTRAINT [PK_PROVEEDORES]
    PRIMARY KEY CLUSTERED ([ID_PROVEEDOR] ASC);
GO

-- Creating primary key on [ID_EMPLEADO] in table 'EMPLEADOS'
ALTER TABLE [dbo].[EMPLEADOS]
ADD CONSTRAINT [PK_EMPLEADOS]
    PRIMARY KEY CLUSTERED ([ID_EMPLEADO] ASC);
GO

-- Creating primary key on [ID] in table 'STOCK_BODEGA_PRINCIPAL'
ALTER TABLE [dbo].[STOCK_BODEGA_PRINCIPAL]
ADD CONSTRAINT [PK_STOCK_BODEGA_PRINCIPAL]
    PRIMARY KEY CLUSTERED ([ID] ASC);
GO

-- Creating primary key on [ROLES_ID_ROL], [USUARIOS_ID_USUARIO] in table 'ROLUSUARIO'
ALTER TABLE [dbo].[ROLUSUARIO]
ADD CONSTRAINT [PK_ROLUSUARIO]
    PRIMARY KEY CLUSTERED ([ROLES_ID_ROL], [USUARIOS_ID_USUARIO] ASC);
GO

-- --------------------------------------------------
-- Creating all FOREIGN KEY constraints
-- --------------------------------------------------

-- Creating foreign key on [ID_ITEM] in table 'DETALLES_COMPRAS'
ALTER TABLE [dbo].[DETALLES_COMPRAS]
ADD CONSTRAINT [FK_DETALLE_COMPRAITEM]
    FOREIGN KEY ([ID_ITEM])
    REFERENCES [dbo].[ITEMS]
        ([ID_ITEM])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_DETALLE_COMPRAITEM'
CREATE INDEX [IX_FK_DETALLE_COMPRAITEM]
ON [dbo].[DETALLES_COMPRAS]
    ([ID_ITEM]);
GO

-- Creating foreign key on [ID_COMPRA] in table 'DETALLES_COMPRAS'
ALTER TABLE [dbo].[DETALLES_COMPRAS]
ADD CONSTRAINT [FK_COMPRADETALLE_COMPRA]
    FOREIGN KEY ([ID_COMPRA])
    REFERENCES [dbo].[COMPRAS]
        ([ID_COMPRA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_COMPRADETALLE_COMPRA'
CREATE INDEX [IX_FK_COMPRADETALLE_COMPRA]
ON [dbo].[DETALLES_COMPRAS]
    ([ID_COMPRA]);
GO

-- Creating foreign key on [ID_RECETA] in table 'DETALLES_RECETAS'
ALTER TABLE [dbo].[DETALLES_RECETAS]
ADD CONSTRAINT [FK_RECETADETALLE_RECETA]
    FOREIGN KEY ([ID_RECETA])
    REFERENCES [dbo].[RECETAS]
        ([ID_RECETA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_RECETADETALLE_RECETA'
CREATE INDEX [IX_FK_RECETADETALLE_RECETA]
ON [dbo].[DETALLES_RECETAS]
    ([ID_RECETA]);
GO

-- Creating foreign key on [ID_ITEM] in table 'DETALLES_RECETAS'
ALTER TABLE [dbo].[DETALLES_RECETAS]
ADD CONSTRAINT [FK_DETALLE_RECETAITEM]
    FOREIGN KEY ([ID_ITEM])
    REFERENCES [dbo].[ITEMS]
        ([ID_ITEM])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_DETALLE_RECETAITEM'
CREATE INDEX [IX_FK_DETALLE_RECETAITEM]
ON [dbo].[DETALLES_RECETAS]
    ([ID_ITEM]);
GO

-- Creating foreign key on [ROLES_ID_ROL] in table 'ROLUSUARIO'
ALTER TABLE [dbo].[ROLUSUARIO]
ADD CONSTRAINT [FK_ROLUSUARIO_ROL]
    FOREIGN KEY ([ROLES_ID_ROL])
    REFERENCES [dbo].[ROLES]
        ([ID_ROL])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating foreign key on [USUARIOS_ID_USUARIO] in table 'ROLUSUARIO'
ALTER TABLE [dbo].[ROLUSUARIO]
ADD CONSTRAINT [FK_ROLUSUARIO_USUARIO]
    FOREIGN KEY ([USUARIOS_ID_USUARIO])
    REFERENCES [dbo].[USUARIOS]
        ([ID_USUARIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ROLUSUARIO_USUARIO'
CREATE INDEX [IX_FK_ROLUSUARIO_USUARIO]
ON [dbo].[ROLUSUARIO]
    ([USUARIOS_ID_USUARIO]);
GO

-- Creating foreign key on [ID_USUARIO] in table 'COMPRAS'
ALTER TABLE [dbo].[COMPRAS]
ADD CONSTRAINT [FK_COMPRAUSUARIO]
    FOREIGN KEY ([ID_USUARIO])
    REFERENCES [dbo].[USUARIOS]
        ([ID_USUARIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_COMPRAUSUARIO'
CREATE INDEX [IX_FK_COMPRAUSUARIO]
ON [dbo].[COMPRAS]
    ([ID_USUARIO]);
GO

-- Creating foreign key on [ID_PRODUCCION] in table 'DETALLES_PRODUCCIONES'
ALTER TABLE [dbo].[DETALLES_PRODUCCIONES]
ADD CONSTRAINT [FK_PRODUCCIONDETALLE_PRODUCCION]
    FOREIGN KEY ([ID_PRODUCCION])
    REFERENCES [dbo].[PRODUCCIONES]
        ([ID_PRODUCCION])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PRODUCCIONDETALLE_PRODUCCION'
CREATE INDEX [IX_FK_PRODUCCIONDETALLE_PRODUCCION]
ON [dbo].[DETALLES_PRODUCCIONES]
    ([ID_PRODUCCION]);
GO

-- Creating foreign key on [ID_RECETA] in table 'DETALLES_PRODUCCIONES'
ALTER TABLE [dbo].[DETALLES_PRODUCCIONES]
ADD CONSTRAINT [FK_RECETADETALLE_PRODUCCION]
    FOREIGN KEY ([ID_RECETA])
    REFERENCES [dbo].[RECETAS]
        ([ID_RECETA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_RECETADETALLE_PRODUCCION'
CREATE INDEX [IX_FK_RECETADETALLE_PRODUCCION]
ON [dbo].[DETALLES_PRODUCCIONES]
    ([ID_RECETA]);
GO

-- Creating foreign key on [ID_USUARIO] in table 'PRODUCCIONES'
ALTER TABLE [dbo].[PRODUCCIONES]
ADD CONSTRAINT [FK_PRODUCCIONUSUARIO]
    FOREIGN KEY ([ID_USUARIO])
    REFERENCES [dbo].[USUARIOS]
        ([ID_USUARIO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_PRODUCCIONUSUARIO'
CREATE INDEX [IX_FK_PRODUCCIONUSUARIO]
ON [dbo].[PRODUCCIONES]
    ([ID_USUARIO]);
GO

-- Creating foreign key on [ID_MEDIDA] in table 'ITEMS'
ALTER TABLE [dbo].[ITEMS]
ADD CONSTRAINT [FK_ITEMMEDIDA]
    FOREIGN KEY ([ID_MEDIDA])
    REFERENCES [dbo].[MEDIDAS]
        ([ID_MEDIDA])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ITEMMEDIDA'
CREATE INDEX [IX_FK_ITEMMEDIDA]
ON [dbo].[ITEMS]
    ([ID_MEDIDA]);
GO

-- Creating foreign key on [ITEM_ID_ITEM] in table 'STOCK_PRODUCCION'
ALTER TABLE [dbo].[STOCK_PRODUCCION]
ADD CONSTRAINT [FK_ITEMSTOCK_PRODUCCION]
    FOREIGN KEY ([ITEM_ID_ITEM])
    REFERENCES [dbo].[ITEMS]
        ([ID_ITEM])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ITEMSTOCK_PRODUCCION'
CREATE INDEX [IX_FK_ITEMSTOCK_PRODUCCION]
ON [dbo].[STOCK_PRODUCCION]
    ([ITEM_ID_ITEM]);
GO

-- Creating foreign key on [ID_PROVEEDOR] in table 'COMPRAS'
ALTER TABLE [dbo].[COMPRAS]
ADD CONSTRAINT [FK_COMPRAPROVEEDOR]
    FOREIGN KEY ([ID_PROVEEDOR])
    REFERENCES [dbo].[PROVEEDORES]
        ([ID_PROVEEDOR])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_COMPRAPROVEEDOR'
CREATE INDEX [IX_FK_COMPRAPROVEEDOR]
ON [dbo].[COMPRAS]
    ([ID_PROVEEDOR]);
GO

-- Creating foreign key on [ITEM_ID_ITEM] in table 'STOCK_BODEGA_PRINCIPAL'
ALTER TABLE [dbo].[STOCK_BODEGA_PRINCIPAL]
ADD CONSTRAINT [FK_ITEMSTOCK_BODEGA_PRINCIPAL]
    FOREIGN KEY ([ITEM_ID_ITEM])
    REFERENCES [dbo].[ITEMS]
        ([ID_ITEM])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_ITEMSTOCK_BODEGA_PRINCIPAL'
CREATE INDEX [IX_FK_ITEMSTOCK_BODEGA_PRINCIPAL]
ON [dbo].[STOCK_BODEGA_PRINCIPAL]
    ([ITEM_ID_ITEM]);
GO

-- Creating foreign key on [ID_EMPLEADO] in table 'DETALLES_PRODUCCIONES'
ALTER TABLE [dbo].[DETALLES_PRODUCCIONES]
ADD CONSTRAINT [FK_EMPLEADODETALLE_PRODUCCION]
    FOREIGN KEY ([ID_EMPLEADO])
    REFERENCES [dbo].[EMPLEADOS]
        ([ID_EMPLEADO])
    ON DELETE NO ACTION ON UPDATE NO ACTION;
GO

-- Creating non-clustered index for FOREIGN KEY 'FK_EMPLEADODETALLE_PRODUCCION'
CREATE INDEX [IX_FK_EMPLEADODETALLE_PRODUCCION]
ON [dbo].[DETALLES_PRODUCCIONES]
    ([ID_EMPLEADO]);
GO

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------