//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROASOFT.CapaInfraestructura.SqlEntityFramework.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using PROASOFT.CapaDominio.Entidades;
    
    public partial class ModeloProasoftContainer : DbContext
    {
        public ModeloProasoftContainer()
            : base("name=ModeloProasoftContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ITEM> ITEMS { get; set; }
        public virtual DbSet<COMPRA> COMPRAS { get; set; }
        public virtual DbSet<DETALLE_COMPRA> DETALLES_COMPRAS { get; set; }
        public virtual DbSet<RECETA> RECETAS { get; set; }
        public virtual DbSet<DETALLE_RECETA> DETALLES_RECETAS { get; set; }
        public virtual DbSet<USUARIO> USUARIOS { get; set; }
        public virtual DbSet<ROL> ROLES { get; set; }
        public virtual DbSet<PRODUCCION> PRODUCCIONES { get; set; }
        public virtual DbSet<DETALLE_PRODUCCION> DETALLES_PRODUCCIONES { get; set; }
        public virtual DbSet<MEDIDA> MEDIDAS { get; set; }
        public virtual DbSet<STOCK_PRODUCCION> STOCK_PRODUCCION { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDORES { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADOS { get; set; }
        public virtual DbSet<STOCK_BODEGA_PRINCIPAL> STOCK_BODEGA_PRINCIPAL { get; set; }
    }
}
