//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 

namespace FacturacionElectronica.Proxys.Autorizacion
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "AutorizacionComprobantesServiceSoapBinding", Namespace = "http://ec.gob.sri.ws.autorizacion")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensaje[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(autorizacion[]))]
    public partial class AutorizacionComprobantesService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback autorizacionComprobanteOperationCompleted;

        private System.Threading.SendOrPostCallback autorizacionComprobanteLoteOperationCompleted;

        /// <remarks/>
        public AutorizacionComprobantesService()
        {
            this.Url = "https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantes";
        }

        /// <remarks/>
        public event autorizacionComprobanteCompletedEventHandler autorizacionComprobanteCompleted;

        /// <remarks/>
        public event autorizacionComprobanteLoteCompletedEventHandler autorizacionComprobanteLoteCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://ec.gob.sri.ws.autorizacion", ResponseNamespace = "http://ec.gob.sri.ws.autorizacion", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("RespuestaAutorizacionComprobante", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] autorizacionComprobante([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string claveAccesoComprobante)
        {
            object[] results = this.Invoke("autorizacionComprobante", new object[] {
                    claveAccesoComprobante});
            // return ((respuestaComprobante)(results[0]));
            return results;
        }

        /// <remarks/>
        public System.IAsyncResult BeginautorizacionComprobante(string claveAccesoComprobante, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("autorizacionComprobante", new object[] {
                    claveAccesoComprobante}, callback, asyncState);
        }

        /// <remarks/>
        public respuestaComprobante EndautorizacionComprobante(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((respuestaComprobante)(results[0]));
        }

        /// <remarks/>
        public void autorizacionComprobanteAsync(string claveAccesoComprobante)
        {
            this.autorizacionComprobanteAsync(claveAccesoComprobante, null);
        }

        /// <remarks/>
        public void autorizacionComprobanteAsync(string claveAccesoComprobante, object userState)
        {
            if ((this.autorizacionComprobanteOperationCompleted == null))
            {
                this.autorizacionComprobanteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnautorizacionComprobanteOperationCompleted);
            }
            this.InvokeAsync("autorizacionComprobante", new object[] {
                    claveAccesoComprobante}, this.autorizacionComprobanteOperationCompleted, userState);
        }

        private void OnautorizacionComprobanteOperationCompleted(object arg)
        {
            if ((this.autorizacionComprobanteCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.autorizacionComprobanteCompleted(this, new autorizacionComprobanteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://ec.gob.sri.ws.autorizacion", ResponseNamespace = "http://ec.gob.sri.ws.autorizacion", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("RespuestaAutorizacionLote", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public respuestaLote autorizacionComprobanteLote([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] string claveAccesoLote)
        {
            object[] results = this.Invoke("autorizacionComprobanteLote", new object[] {
                    claveAccesoLote});
            return ((respuestaLote)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginautorizacionComprobanteLote(string claveAccesoLote, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("autorizacionComprobanteLote", new object[] {
                    claveAccesoLote}, callback, asyncState);
        }

        /// <remarks/>
        public respuestaLote EndautorizacionComprobanteLote(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((respuestaLote)(results[0]));
        }

        /// <remarks/>
        public void autorizacionComprobanteLoteAsync(string claveAccesoLote)
        {
            this.autorizacionComprobanteLoteAsync(claveAccesoLote, null);
        }

        /// <remarks/>
        public void autorizacionComprobanteLoteAsync(string claveAccesoLote, object userState)
        {
            if ((this.autorizacionComprobanteLoteOperationCompleted == null))
            {
                this.autorizacionComprobanteLoteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnautorizacionComprobanteLoteOperationCompleted);
            }
            this.InvokeAsync("autorizacionComprobanteLote", new object[] {
                    claveAccesoLote}, this.autorizacionComprobanteLoteOperationCompleted, userState);
        }

        private void OnautorizacionComprobanteLoteOperationCompleted(object arg)
        {
            if ((this.autorizacionComprobanteLoteCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.autorizacionComprobanteLoteCompleted(this, new autorizacionComprobanteLoteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.gob.sri.ws.autorizacion")]
    public partial class respuestaComprobante
    {

        private string claveAccesoConsultadaField;

        private string numeroComprobantesField;

        private autorizacion[] autorizacionesField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string claveAccesoConsultada
        {
            get
            {
                return this.claveAccesoConsultadaField;
            }
            set
            {
                this.claveAccesoConsultadaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string numeroComprobantes
        {
            get
            {
                return this.numeroComprobantesField;
            }
            set
            {
                this.numeroComprobantesField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public autorizacion[] autorizaciones
        {
            get
            {
                return this.autorizacionesField;
            }
            set
            {
                this.autorizacionesField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.gob.sri.ws.autorizacion")]
    public partial class autorizacion
    {

        private string estadoField;

        private string numeroAutorizacionField;

        private System.DateTime fechaAutorizacionField;

        private bool fechaAutorizacionFieldSpecified;

        private string ambienteField;

        private string comprobanteField;

        private mensaje[] mensajesField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string numeroAutorizacion
        {
            get
            {
                return this.numeroAutorizacionField;
            }
            set
            {
                this.numeroAutorizacionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public System.DateTime fechaAutorizacion
        {
            get
            {
                return this.fechaAutorizacionField;
            }
            set
            {
                this.fechaAutorizacionField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaAutorizacionSpecified
        {
            get
            {
                return this.fechaAutorizacionFieldSpecified;
            }
            set
            {
                this.fechaAutorizacionFieldSpecified = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string ambiente
        {
            get
            {
                return this.ambienteField;
            }
            set
            {
                this.ambienteField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string comprobante
        {
            get
            {
                return this.comprobanteField;
            }
            set
            {
                this.comprobanteField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public mensaje[] mensajes
        {
            get
            {
                return this.mensajesField;
            }
            set
            {
                this.mensajesField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.gob.sri.ws.autorizacion")]
    public partial class mensaje
    {

        private string identificadorField;

        private string mensaje1Field;

        private string informacionAdicionalField;

        private string tipoField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string identificador
        {
            get
            {
                return this.identificadorField;
            }
            set
            {
                this.identificadorField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("mensaje", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string mensaje1
        {
            get
            {
                return this.mensaje1Field;
            }
            set
            {
                this.mensaje1Field = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string informacionAdicional
        {
            get
            {
                return this.informacionAdicionalField;
            }
            set
            {
                this.informacionAdicionalField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.gob.sri.ws.autorizacion")]
    public partial class respuestaLote
    {

        private string claveAccesoLoteConsultadaField;

        private string numeroComprobantesLoteField;

        private autorizacion[] autorizacionesField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string claveAccesoLoteConsultada
        {
            get
            {
                return this.claveAccesoLoteConsultadaField;
            }
            set
            {
                this.claveAccesoLoteConsultadaField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string numeroComprobantesLote
        {
            get
            {
                return this.numeroComprobantesLoteField;
            }
            set
            {
                this.numeroComprobantesLoteField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public autorizacion[] autorizaciones
        {
            get
            {
                return this.autorizacionesField;
            }
            set
            {
                this.autorizacionesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void autorizacionComprobanteCompletedEventHandler(object sender, autorizacionComprobanteCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class autorizacionComprobanteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal autorizacionComprobanteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public respuestaComprobante Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((respuestaComprobante)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void autorizacionComprobanteLoteCompletedEventHandler(object sender, autorizacionComprobanteLoteCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class autorizacionComprobanteLoteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal autorizacionComprobanteLoteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public respuestaLote Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((respuestaLote)(this.results[0]));
            }
        }
    }
}
