//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int IdChat { get; set; }
        public int IdUser { get; set; }
        public string Message { get; set; }
        public int IdRoom { get; set; }
        public bool IsEvent { get; set; }
    
        public virtual User User { get; set; }
        public virtual Room Room { get; set; }
    }
}
