//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEVENC.Dominio.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class Auditoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auditoria()
        {
            this.DetallesAuditorias = new HashSet<DetalleAuditoria>();
        }
    
    
        [DataMember]
        public int IdAuditoria { get; set; }
    
        [DataMember]
        public System.DateTime Fecha { get; set; }
    
        [DataMember]
        public int IdUsuario { get; set; }
    
        [DataMember]
        public int IdOperacion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Operacion Operacion { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleAuditoria> DetallesAuditorias { get; set; }
    }
}
