//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEVENC.Dominio.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class DetalleAuditoria
    {
    
        [DataMember]
        public long IdDetalleAuditoria { get; set; }
    
        [DataMember]
        public string Entidad { get; set; }
    
        [DataMember]
        public string ClaveEntidad { get; set; }
    
        [DataMember]
        public string Campo { get; set; }
    
        [DataMember]
        public string ValorAntiguo { get; set; }
    
        [DataMember]
        public string ValorNuevo { get; set; }
    
        [DataMember]
        public int IdAuditoria { get; set; }
    
        public virtual Auditoria Auditoria { get; set; }
    }
}
