//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEVENC.Dominio.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.Sucursales = new HashSet<Sucursal>();
            this.Usuarios = new HashSet<Usuario>();
        }
    
    
        [DataMember]
        public byte IdEmpresa { get; set; }
    
        [DataMember]
        public string RazonSocial { get; set; }
    
        [DataMember]
        public string NombreComercial { get; set; }
    
        [DataMember]
        public string RUC { get; set; }
    
        [DataMember]
        public string IdRepresentanteLegal { get; set; }
    
        [DataMember]
        public string NombreRepresentanteLegal { get; set; }
    
        [DataMember]
        public bool EstaActiva { get; set; }
    
        [DataMember]
        public bool EstaEliminada { get; set; }
    
        [DataMember]
        public byte[] Concurrencia { get; set; }
    
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sucursal> Sucursales { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
