//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEVENC.Dominio.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class Error
    {
    
        [DataMember]
        public int IdError { get; set; }
    
        [DataMember]
        public string Tipo { get; set; }
    
        [DataMember]
        public System.DateTime Fecha { get; set; }
    
        [DataMember]
        public string Mensaje { get; set; }
    
        [DataMember]
        public string Detalle { get; set; }
    }
}
