//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEVENC.Dominio.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class Rol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rol()
        {
            this.Usuarios = new HashSet<Usuario>();
            this.Operaciones = new HashSet<Operacion>();
        }
    
    
        [DataMember]
        public int IdRol { get; set; }
    
        [DataMember]
        public string Nombre { get; set; }
    
        [DataMember]
        public string Descripcion { get; set; }
    
        [DataMember]
        public bool EstaActivo { get; set; }
    
        [DataMember]
        public bool EsSistema { get; set; }
    
        [DataMember]
        public byte[] Concurrencia { get; set; }
    
        [DataMember]
        public bool EstaEliminado { get; set; }
    
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuarios { get; set; }
        [DataMember]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operacion> Operaciones { get; set; }
    }
}
