//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEVENC.Dominio.Entidades
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference=true)]
    public partial class SesionUsuario
    {
    
        [DataMember]
        public long IdSesion { get; set; }
    
        [DataMember]
        public System.DateTime FechaInicio { get; set; }
    
        [DataMember]
        public Nullable<System.DateTime> FechaFin { get; set; }
    
        [DataMember]
        public string Ip { get; set; }
    
        [DataMember]
        public int IdUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
