//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domosti.CapaDatos.Modelos
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class Dispositivo
    {
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dispositivo()
        {
            this.DispositivoResidenteViviendas = new HashSet<DispositivoResidenteVivienda>();
            this.Permisos = new HashSet<Permiso>();
        }
    
        public int IdDispositivo { get; set; }
        public string IdDevice { get; set; }
        public string Imei { get; set; }
        public string IccId { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int IdUsuarioApp { get; set; }
        public byte[] UpdateToken { get; set; }
        public string Token { get; set; }
    
        public virtual UsuarioApp UsuarioApp { get; set; }
        public virtual ICollection<DispositivoResidenteVivienda> DispositivoResidenteViviendas { get; set; }
        public virtual ICollection<Permiso> Permisos { get; set; }
    }
}
