//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domosti.CapaDatos.Modelos
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class DispositivoResidenteVivienda
    {
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DispositivoResidenteVivienda()
        {
            this.AuditoriaDrvs = new HashSet<AuditoriaDrv>();
        }
    
        public long Id { get; set; }
        public string Estado { get; set; }
        public int IdVivienda { get; set; }
        public int IdResidente { get; set; }
        public int IdDispositivo { get; set; }
    
        public virtual Vivienda Vivienda { get; set; }
        public virtual Residente Residente { get; set; }
        public virtual Dispositivo Dispositivo { get; set; }
        public virtual ICollection<AuditoriaDrv> AuditoriaDrvs { get; set; }
    }
}
