//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domosti.CapaDatos.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloDomostiContainer : DbContext
    {
    
        public ModeloDomostiContainer()
            : base("name=ModeloDomostiContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ciudadela> Ciudadelas { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<Vivienda> Viviendas { get; set; }
        public DbSet<Persona> Personas { get; set; }
        public DbSet<FotoResidente> FotosResidentes { get; set; }
        public DbSet<Dispositivo> Dispositivos { get; set; }
        public DbSet<DispositivoResidenteVivienda> DispositivoResidenteViviendas { get; set; }
        public DbSet<AuditoriaDrv> AuditoriaDrvs { get; set; }
        public DbSet<CabeceraPermiso> CabecerasPermisos { get; set; }
        public DbSet<Permiso> Permisos { get; set; }
        public DbSet<MotivoAcceso> MotivosAccesos { get; set; }
        public DbSet<AuditoriaPermiso> AuditoriaPermisos { get; set; }
        public DbSet<PermisoManual> PermisosManuales { get; set; }
        public DbSet<Acceso> Accesos { get; set; }
        public DbSet<Error> Errores { get; set; }
        public DbSet<Notificacion> Notificaciones { get; set; }
    }
}
