//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domosti.CapaDatos.Modelos
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class MotivoAcceso
    {
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MotivoAcceso()
        {
            this.Permisos = new HashSet<Permiso>();
            this.PermisosManuales = new HashSet<PermisoManual>();
        }
    
        public short IdMotivoAcceso { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Permiso> Permisos { get; set; }
        public virtual ICollection<PermisoManual> PermisosManuales { get; set; }
    }
}
