//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domosti.CapaDatos.Modelos
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class PermisoManual
    {
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public int IdPermisoManual { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string Observaciones { get; set; }
        public string CedulaVisitante { get; set; }
        public string NombreVisitante { get; set; }
        public int IdResidente { get; set; }
        public short IdMotivoAcceso { get; set; }
        public int IdVivienda { get; set; }
    
        public virtual Residente Residente { get; set; }
        public virtual MotivoAcceso MotivoAcceso { get; set; }
        public virtual Vivienda Vivienda { get; set; }
    }
}
