//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domosti.CapaDatos.Modelos
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class Residente : Persona
    {
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Residente()
        {
            this.Visitantes = new HashSet<Visitante>();
            this.Viviendas = new HashSet<Vivienda>();
            this.DispositivoResidenteViviendas = new HashSet<DispositivoResidenteVivienda>();
            this.Permisos = new HashSet<Permiso>();
            this.PermisosManuales = new HashSet<PermisoManual>();
            this.Notificaciones = new HashSet<Notificacion>();
        }
    
        public System.DateTime FechaNacimiento { get; set; }
        public string TelefonoMovil { get; set; }
        public bool EstaActivo { get; set; }
        public bool PuedeUsarApp { get; set; }
        public bool EstaEliminado { get; set; }
        public Nullable<int> IdUsuarioApp { get; set; }
        public bool PoseeDeudas { get; set; }
    
        public virtual FotoResidente FotoResidente { get; set; }
        public virtual UsuarioApp UsuarioApp { get; set; }
        public virtual ICollection<Visitante> Visitantes { get; set; }
        public virtual ICollection<Vivienda> Viviendas { get; set; }
        public virtual ICollection<DispositivoResidenteVivienda> DispositivoResidenteViviendas { get; set; }
        public virtual ICollection<Permiso> Permisos { get; set; }
        public virtual ICollection<PermisoManual> PermisosManuales { get; set; }
        public virtual ICollection<Notificacion> Notificaciones { get; set; }
    }
}
