//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domosti.CapaDatos.Modelos
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class Usuario
    {
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public int IdUsuario { get; set; }
        public string Tipo { get; set; }
        public string UserName { get; set; }
        public string Contrasena { get; set; }
        public int IdCiudadela { get; set; }
    
        public virtual Ciudadela Ciudadela { get; set; }
    }
}
