//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROASOFT.CapaDominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_COMPRA
    {
        public long ID_DETALLE { get; set; }
        public short CANTIDAD { get; set; }
        public decimal PRECIO { get; set; }
        public int ID_ITEM { get; set; }
        public int ID_COMPRA { get; set; }
    
        public virtual ITEM ITEM { get; set; }
        public virtual COMPRA COMPRA { get; set; }
    }
}
