//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROASOFT.CapaDominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITEM()
        {
            this.DETALLES_COMPRAS = new HashSet<DETALLE_COMPRA>();
            this.DETALLES_RECETAS = new HashSet<DETALLE_RECETA>();
        }
    
        public int ID_ITEM { get; set; }
        public string NOMBRE { get; set; }
        public bool ESTA_ACTIVO { get; set; }
        public byte ID_MEDIDA { get; set; }
        public decimal COSTO_POR_KILOGRAMO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_COMPRA> DETALLES_COMPRAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_RECETA> DETALLES_RECETAS { get; set; }
        public virtual MEDIDA MEDIDA { get; set; }
        public virtual STOCK_PRODUCCION STOCK_PRODUCCION { get; set; }
        public virtual STOCK_BODEGA_PRINCIPAL STOCK_BODEGA_PRINCIPAL { get; set; }
    }
}
