//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROASOFT.CapaDominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class STOCK_PRODUCCION
    {
        public int ID { get; set; }
        public double CANTIDAD { get; set; }
        public double CANTIDAD_ORDEN_PRODUCCION { get; set; }
    
        public virtual ITEM ITEM { get; set; }
    }
}
