//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEVENC.Infraestructura.SqlEntityFramework.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using SEVENC.Dominio.Entidades;
    
    public partial class ModeloDatosContainer : DbContext
    {
        public ModeloDatosContainer()
            : base("name=ModeloDatosContainer")
        {
            Configuration.LazyLoadingEnabled = false;
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<Sucursal> Sucursales { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Error> Errores { get; set; }
        public virtual DbSet<Rol> Roles { get; set; }
        public virtual DbSet<Operacion> Operaciones { get; set; }
        public virtual DbSet<SesionUsuario> SesionesUsuarios { get; set; }
        public virtual DbSet<Auditoria> Auditorias { get; set; }
        public virtual DbSet<DetalleAuditoria> DetallesAuditorias { get; set; }
    }
}
