//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 

namespace FacturacionElectronica.Proxys.Recepcion
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "RecepcionComprobantesServiceSoapBinding", Namespace = "http://ec.gob.sri.ws.recepcion")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensaje[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(comprobante[]))]
    public partial class RecepcionComprobantesService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback validarComprobanteOperationCompleted;

        /// <remarks/>
        public RecepcionComprobantesService()
        {
            this.Url = "https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantes";
        }

        /// <remarks/>
        public event validarComprobanteCompletedEventHandler validarComprobanteCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://ec.gob.sri.ws.recepcion", ResponseNamespace = "http://ec.gob.sri.ws.recepcion", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("RespuestaRecepcionComprobante", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] validarComprobante([System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "base64Binary")] byte[] xml)
        {
            object[] results = this.Invoke("validarComprobante", new object[] {
                    xml});
            //return ((respuestaSolicitud)(results[0]));
            return results;
        }

        /// <remarks/>
        public System.IAsyncResult BeginvalidarComprobante(byte[] xml, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("validarComprobante", new object[] {
                    xml}, callback, asyncState);
        }

        /// <remarks/>
        public respuestaSolicitud EndvalidarComprobante(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((respuestaSolicitud)(results[0]));
        }

        /// <remarks/>
        public void validarComprobanteAsync(byte[] xml)
        {
            this.validarComprobanteAsync(xml, null);
        }

        /// <remarks/>
        public void validarComprobanteAsync(byte[] xml, object userState)
        {
            if ((this.validarComprobanteOperationCompleted == null))
            {
                this.validarComprobanteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidarComprobanteOperationCompleted);
            }
            this.InvokeAsync("validarComprobante", new object[] {
                    xml}, this.validarComprobanteOperationCompleted, userState);
        }

        private void OnvalidarComprobanteOperationCompleted(object arg)
        {
            if ((this.validarComprobanteCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validarComprobanteCompleted(this, new validarComprobanteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.gob.sri.ws.recepcion")]
    public partial class respuestaSolicitud
    {

        private string estadoField;

        private comprobante[] comprobantesField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public comprobante[] comprobantes
        {
            get
            {
                return this.comprobantesField;
            }
            set
            {
                this.comprobantesField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.gob.sri.ws.recepcion")]
    public partial class comprobante
    {

        private string claveAccesoField;

        private mensaje[] mensajesField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string claveAcceso
        {
            get
            {
                return this.claveAccesoField;
            }
            set
            {
                this.claveAccesoField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public mensaje[] mensajes
        {
            get
            {
                return this.mensajesField;
            }
            set
            {
                this.mensajesField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.gob.sri.ws.recepcion")]
    public partial class mensaje
    {

        private string identificadorField;

        private string mensaje1Field;

        private string informacionAdicionalField;

        private string tipoField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string identificador
        {
            get
            {
                return this.identificadorField;
            }
            set
            {
                this.identificadorField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("mensaje", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string mensaje1
        {
            get
            {
                return this.mensaje1Field;
            }
            set
            {
                this.mensaje1Field = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string informacionAdicional
        {
            get
            {
                return this.informacionAdicionalField;
            }
            set
            {
                this.informacionAdicionalField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void validarComprobanteCompletedEventHandler(object sender, validarComprobanteCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validarComprobanteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal validarComprobanteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public respuestaSolicitud Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((respuestaSolicitud)(this.results[0]));
            }
        }
    }
}
